image:
    file: .gitpod.Dockerfile

vscode:
  extensions:
    - runem.lit-plugin
    - tabnine.tabnine-vscode
    - eamodio.gitlens
tasks:
  - name: Install and run test
    init: |
      npm install
      gp sync-done install
    command: npm run test
    openMode: tab-after
